export default {
	name: "BeyondChats",
	themeBackground: "#2872FA",
	themeColor: "#fff",
	chatColor: "#1d1d1d",
	chatBackground: "#ecf4e5",
	img: null,
	fontDifference: 0,
	positionLeft: "auto",
	positionBottom: 25,
	positionRight: 25,
	suggestedQuestions: ["What is your product?"],
	askEmail: false,
	useVerticalSuggestions: false,
	welcomeText: ["Hi there! How can I help you today?"],
	showBubble: true,
	loader: "",
	open: true,
	icon: "https://integration.beyondchats.com/favicon.png",
};
